In [11]:

from math import sqrt
from scipy import stats

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pydataset import data
import statistics
import seaborn as sns

# 𝐻0  There is no association between using a macbook and being a codeup student (independence)
# 𝐻𝑎  is that there is a association between using a macbook and being a codeup student

In [40]:
macbook = pd.DataFrame([[49, 20], [1, 30]],
                      index = ['uses a macbook', 'doesnt use a macbook'],
                      columns= ['codeup student', 'not codeup student'])
macbook

codeup student  not codeup student
uses a macbook                    49                  20
doesnt use a macbook               1                  30

In [44]:
chi2, p, degf, expected = stats.chi2_contingency(macbook)


In [45]:
print('Observed\n')
print(observed.values)
print('---\nExpected\n')
print(expected.astype(int))
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[ 5864 20854]
 [ 8978 31391]]
---
Expected

[[34 34]
 [15 15]]
---

chi^2 = 36.6526
p     = 0.0000


In [43]:
alpha = 0.05
if p < alpha:
    print("We reject the hypothesis")
else:
    print("We fail to reject the null hypothesis")

We reject the hypothesis


In [49]:
# 2

mpg = data('mpg')
mpg.head(3)

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact

In [50]:
mpg['transmission_type'] = np.where(mpg.trans.str.contains('auto'), 'Auto', 'Manual')


In [51]:
mpg.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class  \
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact   
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact   
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact   
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact   
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact   

  transmission_type  
1              Auto  
2            Manual  
3            Manual  
4              Auto  
5              Auto

In [53]:
mpg.transmission_type.value_counts()

Auto      157
Manual     77
Name: transmission_type, dtype: int64

In [54]:
mpg['drv'].value_counts()

f    106
4    103
r     25
Name: drv, dtype: int64

In [58]:

a = mpg.transmission_type
b = mpg.drv

In [59]:
# h0 Transmission type independent of drive type on vehicles

observed = pd.crosstab(a,b)
observed

drv                 4   f   r
transmission_type            
Auto               75  65  17
Manual             28  41   8

In [60]:
alpha = 0.05

In [61]:
chi2, p, degf, expected = stats.chi2_contingency(observed)

In [62]:
print('Observed\n')
print(observed.values)
print('---\nExpected\n')
print(expected.astype(int))
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[75 65 17]
 [28 41  8]]
---
Expected

[[69 71 16]
 [33 34  8]]
---

chi^2 = 3.1368
p     = 0.2084


In [63]:
if p < alpha:
    print("We reject the hypothesis")
else:
    print("We fail to reject the null hypothesis")

We fail to reject the null hypothesis


In [15]:
# 3


from env1 import host, user, password
import pymysql
url = f'mysql+pymysql://{user}:{password}@{host}/employees'

In [21]:
def get_db_url(db):
    return f'mysql+pymysql://{user}:{password}@{host}/{db}'
query = '''SELECT * FROM employees limit 10'''



In [24]:
employees = pd.read_sql(query, get_db_url('employees'))
employees

emp_no  birth_date first_name  last_name gender   hire_date
0   10001  1953-09-02     Georgi    Facello      M  1986-06-26
1   10002  1964-06-02    Bezalel     Simmel      F  1985-11-21
2   10003  1959-12-03      Parto    Bamford      M  1986-08-28
3   10004  1954-05-01  Chirstian    Koblick      M  1986-12-01
4   10005  1955-01-21    Kyoichi   Maliniak      M  1989-09-12
5   10006  1953-04-20     Anneke    Preusig      F  1989-06-02
6   10007  1957-05-23    Tzvetan  Zielinski      F  1989-02-10
7   10008  1958-02-19     Saniya   Kalloufi      M  1994-09-15
8   10009  1952-04-19     Sumant       Peac      F  1985-02-18
9   10010  1963-06-01  Duangkaew   Piveteau      F  1989-08-24

In [25]:
employees.head()

emp_no  birth_date first_name last_name gender   hire_date
0   10001  1953-09-02     Georgi   Facello      M  1986-06-26
1   10002  1964-06-02    Bezalel    Simmel      F  1985-11-21
2   10003  1959-12-03      Parto   Bamford      M  1986-08-28
3   10004  1954-05-01  Chirstian   Koblick      M  1986-12-01
4   10005  1955-01-21    Kyoichi  Maliniak      M  1989-09-12

In [33]:
e2 = pd.read_sql(query, get_db_url('employees'))
e2

first_name  last_name gender  dept_name
0      Cristinel  Bouloucos      F  Marketing
1        Berhard   McFarlin      M  Marketing
2          Yucel      Auria      F  Marketing
3       Karoline   Cesareni      F  Marketing
4       Nikolaos      Llado      F  Marketing
...          ...        ...    ...        ...
67082   Guozhong     Felder      M      Sales
67083       Gino      Usery      M      Sales
67084     Nathan      Ranta      F      Sales
67085      Rimli     Dusink      F      Sales
67086   Bangqing    Kleiser      F      Sales

[67087 rows x 4 columns]

In [31]:
query = "select first_name, last_name, gender, dept_name from departments join dept_emp de using (dept_no) join employees using (emp_no) where de.to_date > now() and dept_name like 'Marketing%%' or dept_name like 'Sales%%';""

In [34]:
# Is an employee's gender independent of whether an employee works in sales or marketing? (only look at current employees)

observed = pd.crosstab(e2.gender, e2.dept_name)
observed

dept_name  Marketing  Sales
gender                     
F               5864  20854
M               8978  31391

In [35]:
chi2, p, degf, expected = stats.chi2_contingency(observed)

In [36]:
print('Observed\n')
print(observed.values)
print('---\nExpected\n')
print(expected.astype(int))
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[ 5864 20854]
 [ 8978 31391]]
---
Expected

[[ 5910 20807]
 [ 8931 31437]]
---

chi^2 = 0.7793
p     = 0.3774


In [46]:
alpha = 0.05
if p < alpha:
    print('We reject the null')
else:
    print("we fail to reject the null")

We reject the null


In [64]:
# Is an employee's gender independent of whether or not they are or have been a manager?

query = '''SELECT e.emp_no, e.gender, dm.dept_no
FROM employees as e
LEFT JOIN dept_manager AS dm ON e.emp_no = dm.emp_no'''

In [65]:
manager_g = pd.read_sql(query, get_db_url('employees'))
manager_g

emp_no gender dept_no
0        10001      M    None
1        10002      F    None
2        10003      M    None
3        10004      M    None
4        10005      M    None
...        ...    ...     ...
300019  499995      F    None
300020  499996      M    None
300021  499997      M    None
300022  499998      M    None
300023  499999      M    None

[300024 rows x 3 columns]

In [67]:
manager_g.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300024 entries, 0 to 300023
Data columns (total 3 columns):
 #   Column   Non-Null Count   Dtype 
---  ------   --------------   ----- 
 0   emp_no   300024 non-null  int64 
 1   gender   300024 non-null  object
 2   dept_no  24 non-null      object
dtypes: int64(1), object(2)
memory usage: 6.9+ MB


In [69]:
manager_g = manager_g.rename(columns={'dept_no': 'manager'}).fillna(0)

In [70]:
manager_g.head()

emp_no gender manager
0   10001      M       0
1   10002      F       0
2   10003      M       0
3   10004      M       0
4   10005      M       0

In [71]:
manager_g['manager'] = np.where(manager_g.manager == 0, 0, 1)

In [72]:
manager_g.manager.value_counts()

0    300000
1        24
Name: manager, dtype: int64

In [73]:
observed = pd.crosstab(manager_g['gender'], manager_g['manager'])
observed

manager       0   1
gender             
F        120038  13
M        179962  11

In [74]:

chi2, p, degf, expected = stats.chi2_contingency(observed)

print('Observed\n:')
print(observed.values)
print('------------------------\nExpected: \n')
print(expected.astype(int))
print('------------------------\n')
print(f'chi2 = {chi2:.2f}')
print(f'p value: {p:.4f}')
if p < alpha:
      print('We can reject the null hypothesis')
else:
    print('We fail to reject the null hypothesis')

Observed
:
[[120038     13]
 [179962     11]]
------------------------
Expected: 

[[120041      9]
 [179958     14]]
------------------------

chi2 = 1.46
p value: 0.2275
We fail to reject the null hypothesis
