In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
np.random.seed(29)

In [3]:
#1
roll = np.random.choice([1,2,3,4,5,6], size = (10_000, 2))
roll

array([[3, 3],
       [3, 3],
       [2, 1],
       ...,
       [5, 6],
       [5, 1],
       [3, 6]])

In [5]:
(roll[:,0] == roll[:,1]).mean()

0.1716

In [7]:
#2

flip = np.random.choice([0,1], size = (10_000, 8))
flip

array([[1, 1, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 1, 0],
       ...,
       [1, 1, 0, ..., 0, 0, 1],
       [1, 1, 1, ..., 1, 0, 1],
       [0, 0, 0, ..., 1, 0, 1]])

In [41]:
(flip.sum(axis = 1) == 3).mean()          

0.2176

In [43]:
# prob of getting > 3 heads
(flip.sum(axis = 1) > 3).mean()

0.6405

In [44]:
# WD = 0, DS = 1
bb = np.random.choice([0, 1], size = (100000, 2), p = [0.75, 0.25])
bb

array([[1, 0],
       [1, 0],
       [1, 0],
       ...,
       [1, 1],
       [0, 1],
       [1, 0]])

In [45]:
p = (bb.sum(axis = 1) == 2).mean()

In [46]:
p/(1-p)

0.06833041323020385

In [10]:
#4

pop = np.random.normal(3, 1.5, size = (10_000, 5))
pop

array([[3.07898772, 2.61033891, 3.23539053, 4.13800932, 3.62732766],
       [2.36067619, 4.2296515 , 3.45551609, 5.79892309, 6.51279368],
       [1.47558409, 3.28685422, 2.69882974, 4.04777301, 4.11039379],
       ...,
       [2.34447006, 5.32011356, 1.61117562, 2.86243164, 3.134255  ],
       [2.38352197, 4.02995486, 3.70894227, 2.50798071, 1.43390253],
       [3.16698862, 3.01944006, 4.40032102, 4.07648934, 3.91113081]])

In [12]:
(pop.sum(axis = 1) < 17).mean()

0.7259

In [13]:
#5

men = np.random.normal(178, 8, size = 10_000)
women = np.random.normal(170, 6, size = 10_000)

In [16]:
(women > men).mean()

0.2141

In [18]:
#6
#0 = no issue, 1 = issue

install = np.random.choice([0,1], size = (10_000, 50), p = [249/250, 1/250])
install

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [19]:
(install.sum(axis = 1) == 0).mean()

0.8236

In [20]:
install_100 = np.random.choice([0,1], size = (10_000, 100), p = [249/250, 1/250])
install_100

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [21]:
# 100 students

(install_100.sum(axis = 1) == 0).mean()

0.6692

In [23]:
install_150 = np.random.choice([0,1], size = (10_000, 150), p = [249/250, 1/250])
install_150

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
#150 students with one issue
(install_150.sum(axis = 1) > 0).mean()

0.4531

In [25]:
#450 students

install_450 = np.random.choice([0,1], size = (10_000, 450), p = [249/250, 1/250])
install_450

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [26]:
(install_450.sum(axis = 1) == 0).mean()

0.1655

In [29]:
# 7
# 0= no truck, 1 = truck shows 

truck = np.random.choice([0 ,1], size = (10_000, 3), p = [0.3, 0.7])
truck

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       ...,
       [0, 1, 1],
       [0, 0, 0],
       [1, 1, 1]])

In [32]:
(truck.sum(axis = 1) == 0).mean()

0.0271

In [33]:
trucks1 = np.random.choice([0 ,1], size = (10_000, 2), p = [0.3, 0.7])
trucks1

array([[1, 0],
       [0, 1],
       [0, 0],
       ...,
       [1, 1],
       [1, 0],
       [1, 1]])

In [35]:

(trucks1.sum(axis = 1) > 0).mean()

0.9079

In [37]:
# 8 

bday = np.random.choice(range(1,366), size = (10_000, 23))
bday

array([[272,  10, 168, ...,  80, 265,   7],
       [281, 327, 211, ...,  77, 169, 347],
       [256, 352, 279, ...,  63, 356,  14],
       ...,
       [ 68, 220,  31, ..., 171, 114,  19],
       [213, 197, 196, ..., 107, 339, 198],
       [301,  25, 119, ..., 348, 107, 339]])

In [39]:
(pd.DataFrame(bday).nunique(axis = 1) < 23).mean()

0.5105